# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gregor PaniÄ - Gameplay Programmer / Designer
email: gregor.panic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gpanic.github.io" # the base hostname & protocol for your site
twitter_username: glhfGreg
github_username:  vision810
collections:
  projects:
    output: true
  code_samples:
    output: true

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: ""